"""empty message

Revision ID: 85215be973a1
Revises: 1a1ab8824729
Create Date: 2024-07-13 07:50:27.041920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85215be973a1'
down_revision = '1a1ab8824729'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_recipes_user_id_users', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_recipes_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
